create table if not exists fund_withdrawals (
    id bigint generated by default as identity primary key,
    date timestamptz not null default timezone('utc'::text, now()),
    fund text not null check (fund in ('utilities', 'labor', 'printer')),
    amount numeric not null default 0 check (amount >= 0),
    withdrawn_by text not null default '',
    purpose text not null default '',
    notes text not null default '',
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table fund_withdrawals enable row level security;

create policy "fund_withdrawals_select_all"
on fund_withdrawals
for select
to anon, authenticated
using (true);

create policy "fund_withdrawals_insert_all"
on fund_withdrawals
for insert
to anon, authenticated
with check (true);

create policy "fund_withdrawals_update_all"
on fund_withdrawals
for update
to anon, authenticated
using (true)
with check (true);

create policy "fund_withdrawals_delete_all"
on fund_withdrawals
for delete
to anon, authenticated
using (true);

create index if not exists fund_withdrawals_date_idx
on fund_withdrawals (date desc);

create index if not exists fund_withdrawals_fund_idx
on fund_withdrawals (fund);