create table if not exists inventory_expenses (
    id bigint generated by default as identity primary key,
    date timestamptz not null default timezone('utc'::text, now()),
    item_name text not null,
    category text not null default 'Other',
    cost numeric not null default 0,
    payer text not null default '',
    notes text not null default '',
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table inventory_expenses enable row level security;

create policy "inventory_expenses_select_all"
on inventory_expenses
for select
to anon, authenticated
using (true);

create policy "inventory_expenses_insert_all"
on inventory_expenses
for insert
to anon, authenticated
with check (true);

create policy "inventory_expenses_update_all"
on inventory_expenses
for update
to anon, authenticated
using (true)
with check (true);

create policy "inventory_expenses_delete_all"
on inventory_expenses
for delete
to anon, authenticated
using (true);

create index if not exists inventory_expenses_date_idx
on inventory_expenses (date desc);
